(define (make-acount balance password)
  (let ((incorrect-count 0)
	(limit 7))
    (define (withdraw amount)
      (if (>= balance amount)
	  (begin (set! balance (- balance amount))
		 balance)
	  "Insufficient funds"))
    (define (deposit amount)
      (set! balance  (+ balance amount)))
    (define (dispatch input-passwd m)
      (if (eq? input-passwd password)
	  (begin (set! incorrect-count 0)
		 (cond ((eq? m 'withdraw) withdraw)
		       ((eq? m 'deposit) deposit)
		       (else (error "Unknow request -- MAKE-ACCOUNT" m))))
	  (lambda (amount)
	    (begin (set! incorrect-count (+ incorrect-count 1))
		   (if (> incorrect-count limit)
		       (call-the-cops))
		   "Incorrect password"))))
    dispatch))

(define (call-the-cops)
  (begin (display "On the way")
	 (newline)))
  
(define acc (make-acount 100 'secret-password))

((acc 'other 'deposit) 1)
